---
MetaDataFormat: "yaml"
license: "MIT"
BaseURL: "https://popmun.do/"
title: "Numeric Grades"
languageCode: "en-us"
theme: "hyde-x"
canonifyURLs: true
relativeURLs: false
disableSitemap: true
contentdir: "content"
layoutdir: "layout"
publishdir: "public"
disableRSS: true
googleAnalytics: "UA-74404787-2"


permalinks:
  post: /:slug/

author:
  name: "Numeric Grades"

params:
  truncate: false
  hideReadingTime: true
  theme: "theme-base-0d"
  home: "English"
  tagline:
    for [Popmundo](http://www.popmundo.com)
  googleAnalytics: "UA-74404787-2"
  github: "https://github.com/behcet/numericgrades"
  rss: false

