#!/usr/bin/env node

var fs = require('fs');

var manifest = fs.readFileSync('./manifest.json', 'utf-8');
manifest = JSON.parse(manifest);
delete manifest.background.persistent;

var out = JSON.stringify(manifest, null, '  ');

fs.writeFileSync('./manifest.json', out);

